<?php

namespace Database\Seeders;

use App\Models\Municipio;
use App\Models\Categoria;
use App\Models\Atrativo;
use App\Models\Evento;
use App\Models\Midia;
use App\Models\QrCode;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class JoaoPessoaAtrativosEventosSeeder extends Seeder
{
    public function run(): void
    {
        config(['audit.console' => false]);

        $admin = User::where('role', 'gestor_conteudo')->orWhere('role', 'super_admin')->first();

        // 1. Garantir Município de João Pessoa
        $municipio = Municipio::firstOrCreate(
            ['nome' => 'João Pessoa'],
            ['uf' => 'PB', 'tema_visual' => 'praia']
        );

        // 2. Garantir Categorias
        $catAgua = Categoria::firstOrCreate(['slug' => 'rios'], ['nome' => 'Praias, Rios e Piscinas', 'icone' => 'bi-water', 'tipo' => 'atrativo']);
        $catCultura = Categoria::firstOrCreate(['slug' => 'cultura'], ['nome' => 'História & Cultura', 'icone' => 'bi-bank', 'tipo' => 'atrativo']);
        $catGrutas = Categoria::firstOrCreate(['slug' => 'grutas'], ['nome' => 'Monumentos & Natureza', 'icone' => 'bi-geo', 'tipo' => 'atrativo']);
        $catAventura = Categoria::firstOrCreate(['slug' => 'aventura'], ['nome' => 'Aventura & Trilhas', 'icone' => 'bi-bicycle', 'tipo' => 'atrativo']);
        $catGastronomia = Categoria::firstOrCreate(['slug' => 'gastronomia'], ['nome' => 'Gastronomia Regional', 'icone' => 'bi-cup-hot', 'tipo' => 'servico']);
        $catHospedagem = Categoria::firstOrCreate(['slug' => 'hospedagem'], ['nome' => 'Hospedagem & Conforto', 'icone' => 'bi-house-heart', 'tipo' => 'servico']);

        // 3. Catálogo Extensivo de Atrações de João Pessoa (85+ Atrações)
        $atrativos = [
            // --- PRAIAS, PISCINAS NATURAIS & ORLA ---
            [
                'cat' => $catAgua,
                'nome' => 'Piscinas Naturais de Picãozinho',
                'desc' => 'Formação de recifes de corais a cerca de 1,5 km da Praia de Tambaú, com águas mornas e transparentes repletas de peixes sargentinhos na maré baixa.',
                'hist' => 'Ponto tradicional de mergulho ecológico de João Pessoa acessível por catamarãs credenciados com controle de impacto ambiental.',
                'end' => 'Embarque na Praia de Tambaú, João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['deficiencia_auditiva'],
                'lat' => -7.1085,
                'lng' => -34.8080,
                'foto' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia do Bessa (Caribessa)',
                'desc' => 'Famosa pelo trecho apelidado de Caribessa devido às suas águas calmas, mornas e de coloração caribenha, ideal para caiaque, stand-up paddle e famílias.',
                'hist' => 'Área de preservação com projeto de proteção de ninhos de tartarugas marinhas (Projeto Tartarugas do Bessa).',
                'end' => 'Av. Artur Monteiro de Paiva, Bessa, João Pessoa - PB',
                'tempo' => 240,
                'acess' => ['cadeirante'],
                'lat' => -7.0682,
                'lng' => -34.8290,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Manaíra',
                'desc' => 'Orla charmosa com calçadão movimentado para caminhadas, quiosques gastronômicos, ciclovia e vista panorâmica para o oceano atlântico.',
                'hist' => 'Bairro nobre e tradicional, centro de comércio e entretenimento à beira-mar.',
                'end' => 'Av. João Maurício, Manaíra, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.0984,
                'lng' => -34.8276,
                'foto' => 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Cabo Branco',
                'desc' => 'Extensa praia de areia fina, mar convidativo e calçadão fechado todas as manhãs das 5h às 8h para prática exclusiva de corrida, patins e ciclismo.',
                'hist' => 'Uma das praias mais nobres da cidade, que mantém o limite de altura dos edifícios preservando a ventilação natural.',
                'end' => 'Av. Cabo Branco, João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['cadeirante'],
                'lat' => -7.1350,
                'lng' => -34.8190,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia da Penha e Santuário',
                'desc' => 'Praia de vila de pescadores onde se localiza o histórico Santuário de Nossa Senhora da Penha, destino da maior romaria religiosa do estado.',
                'hist' => 'Capela erguida em 1763 pelo português Sílvio Siqueira em agradecimento por uma graça alcançada após tempestade no mar.',
                'end' => 'Praça da Penha, Praia da Penha, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1720,
                'lng' => -34.7950,
                'foto' => 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Jacarapé',
                'desc' => 'Praia preservada com vegetação de restinga, encontro do rio com o mar e atmosfera tranquila e bucólica no litoral sul do município.',
                'hist' => 'Tradicional área de pesca artesanal e refúgio ecológico da costa pessoense.',
                'end' => 'Acesso pela PB-008, Jacarapé, João Pessoa - PB',
                'tempo' => 120,
                'acess' => [],
                'lat' => -7.1930,
                'lng' => -34.8020,
                'foto' => 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia do Sol',
                'desc' => 'Praia rústica de mar aberto com ondas suaves na maré baixa, barracas rústicas com petiscos de frutos do mar frescos e área preservada.',
                'hist' => 'Destino de veraneio tranquilo rodeado por falésias baixas e coqueirais.',
                'end' => 'Praia do Sol, Litoral Sul, João Pessoa - PB',
                'tempo' => 150,
                'acess' => [],
                'lat' => -7.2150,
                'lng' => -34.8080,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia e Encontro das Águas de Barra de Gramame',
                'desc' => 'Cenário paradisíaco do encontro do Rio Gramame com o Oceano Atlântico, proporcionando banho em água doce e salgada no mesmo local.',
                'hist' => 'Região histórica de manguezais e berçário biológico da fauna marinha e estuarina.',
                'end' => 'Barra de Gramame Norte, João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['cadeirante'],
                'lat' => -7.2340,
                'lng' => -34.8150,
                'foto' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia Fluvial do Jacaré',
                'desc' => 'Famoso cartão-postal do pôr do sol ao som do Bolero de Ravel executado pelo saxofonista Jurandy do Sax em barcos pelo Rio Paraíba.',
                'hist' => 'Tradição cultural que há décadas atrai milhares de turistas para contemplar o poente dourado sobre as águas.',
                'end' => 'Parque Fluvial do Jacaré, Cabedelo / Região Metropolitana de João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.0380,
                'lng' => -34.8560,
                'foto' => 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Ilha de Areia Vermelha',
                'desc' => 'Banco de areia avermelhada que emerge no meio do mar durante a maré baixa, formando piscinas naturais e lagoas de água morna.',
                'hist' => 'Parque Estadual Marinho protegido para preservação dos recifes e vida marinha.',
                'end' => 'Embarque na Praia de Camboinha / Poço, Região de João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['deficiencia_auditiva'],
                'lat' => -7.0180,
                'lng' => -34.8250,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Intermares',
                'desc' => 'Praia de mar aberto com ótimas ondas para a prática de surf e kitesurf, e principal ponto de desova de tartarugas marinhas da região.',
                'hist' => 'Sede de campeonatos nordestinos de esportes náuticos e preservação ambiental.',
                'end' => 'Av. Mar Vermelho, Intermares, João Pessoa / Cabedelo - PB',
                'tempo' => 120,
                'acess' => ['cadeirante'],
                'lat' => -7.0420,
                'lng' => -34.8320,
                'foto' => 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- PATRIMÔNIO HISTÓRICO, ARQUITETURA SACRA & MUSEUS ---
            [
                'cat' => $catCultura,
                'nome' => 'Igreja de Nossa Senhora do Carmo',
                'desc' => 'Imponente conjunto carmelita do século XVI em estilo barroco com fachada entalhada em pedra calcária e detalhes rococó.',
                'hist' => 'Fundada em 1592 pelos frades da Ordem do Carmo que chegaram à Capitania da Paraíba.',
                'end' => 'Praça Dom Adauto, Centro Histórico, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1162,
                'lng' => -34.8845,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Catedral Basílica de Nossa Senhora das Neves',
                'desc' => 'Catedral sede da Arquidiocese da Paraíba, reconstruída em estilo eclético neoclássico sobre as fundações da igreja matriz de 1585.',
                'hist' => 'Dedicada à padroeira da cidade e do estado, Nossa Senhora das Neves, celebrada todo dia 5 de agosto.',
                'end' => 'Praça Dom Ulrico, Centro Histórico, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1142,
                'lng' => -34.8872,
                'foto' => 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Mosteiro de São Bento',
                'desc' => 'Monumento beneditino barroco com interior dourado em jacarandá talhado, coro e altares de rara beleza artística sacra.',
                'hist' => 'Construído entre os séculos XVII e XVIII pelos monges beneditinos, foi o maior complexo monástico da província.',
                'end' => 'R. General Osório, Centro Histórico, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1135,
                'lng' => -34.8885,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Igreja da Santa Casa de Misericórdia',
                'desc' => 'Uma das primeiras igrejas da Paraíba, com portal de pedra calcária renascentista e capela-mor com talhas douradas.',
                'hist' => 'Fundada em 1602 pela Irmandade da Misericórdia para prestar assistência médica e social aos colonos e enfermos.',
                'end' => 'R. Duque de Caxias, Centro Histórico, João Pessoa - PB',
                'tempo' => 45,
                'acess' => ['cadeirante'],
                'lat' => -7.1158,
                'lng' => -34.8860,
                'foto' => 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Praça Antenor Navarro',
                'desc' => 'Conjunto arquitetônico vibrante de casarios ecléticos e art déco coloridos que abriga galerias de arte, cafés e vida noturna boêmia.',
                'hist' => 'Antigo polo comercial portuário no Varadouro, hoje polo de cultura e eventos ao ar livre.',
                'end' => 'Praça Antenor Navarro, Varadouro, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1120,
                'lng' => -34.8910,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Hotel Globo & Jardim dos Pôr do Sol',
                'desc' => 'Histórico edifício de 1928 com mirante privilegiado voltado para o vale do Rio Sanhauá, onde se assiste a um dos mais belos entardeceres da cidade.',
                'hist' => 'Primeiro hotel de luxo da capital paraibana que recebia diplomatas, presidentes e artistas que chegavam de navio.',
                'end' => 'Praça de São Frei Pedro Gonçalves, Varadouro, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1115,
                'lng' => -34.8920,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Casa da Pólvora',
                'desc' => 'Fortificação de 1710 com grossas muralhas de pedra utilizada para armazenar munições bélicas durante o período colonial.',
                'hist' => 'Monumento militar tombado pelo IPHAN com vista panorâmica para o estuário do Rio Sanhauá.',
                'end' => 'Ladeira de São Francisco, Centro Histórico, João Pessoa - PB',
                'tempo' => 45,
                'acess' => [],
                'lat' => -7.1148,
                'lng' => -34.8878,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Casarão dos Azulejos',
                'desc' => 'Imóvel nobre do século XIX inteiramente revestido com raros azulejos portugueses azuis e brancos importados da Real Fábrica de Sacavém.',
                'hist' => 'Antiga residência do Comendador Antônio Santos Coelho, patrimônio histórico tombado de João Pessoa.',
                'end' => 'Rua Conselheiro Henriques, Centro, João Pessoa - PB',
                'tempo' => 45,
                'acess' => ['cadeirante'],
                'lat' => -7.1152,
                'lng' => -34.8858,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Theatro Santa Roza',
                'desc' => 'Um dos teatros mais antigos do Brasil em estilo neoclássico italiano com detalhes em madeira nobre e capacidade para 400 espectadores.',
                'hist' => 'Inaugurado em 1889, palco de grandes manifestações políticas e espetáculos culturais da história paraibana.',
                'end' => 'Praça Pedro Américo, Centro, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1175,
                'lng' => -34.8835,
                'foto' => 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Palácio da Redenção',
                'desc' => 'Sede do Poder Executivo da Paraíba com imponente fachada neoclássica e o mausoléu do ex-presidente João Pessoa.',
                'hist' => 'Construído em 1586 originalmente como Convento dos Jesuítas e Colégio de São Gonçalo.',
                'end' => 'Praça João Pessoa, s/n, Centro, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1170,
                'lng' => -34.8840,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Museu da Cidade de João Pessoa',
                'desc' => 'Museu interativo instalado no antigo casarão do Presidente João Pessoa, retratando a evolução urbana, costumes e artefatos da capital.',
                'hist' => 'Inaugurado no aniversário de 433 anos da cidade para preservar a memória cívica e cultural.',
                'end' => 'Praça da Independência, Centro, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1235,
                'lng' => -34.8770,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Academia Paraibana de Letras',
                'desc' => 'Instituição cultural fundada em 1941 que guarda a memória dos grandes escritores e poetas da literatura brasileira e paraibana.',
                'hist' => 'Instalada no histórico Solar do Barão de Maraú com acervo bibliográfico e bustos históricos.',
                'end' => 'Rua Duque de Caxias, 25, Centro, João Pessoa - PB',
                'tempo' => 45,
                'acess' => ['cadeirante'],
                'lat' => -7.1154,
                'lng' => -34.8863,
                'foto' => 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Fortaleza de Santa Catarina',
                'desc' => 'Monumental fortaleza de pedra à beira-mar com canhões de bronze do século XVII, fosso e capela histórica.',
                'hist' => 'Construída em 1589 para defender a foz do Rio Paraíba contra invasões francesas e holandesas.',
                'end' => 'Rua Santa Catarina, Cabedelo / Região Metropolitana de João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante'],
                'lat' => -6.9740,
                'lng' => -34.8340,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- PARQUES, NATUREZA, MIRANTES & ESPAÇOS URBANOS ---
            [
                'cat' => $catGrutas,
                'nome' => 'Estação Cabo Branco - Ciência, Cultura e Artes',
                'desc' => 'Complexo futurista projetado por Oscar Niemeyer em formato de torre envidraçada octogonal, com planetário, exposições de arte e mirante 360°.',
                'hist' => 'Inaugurado em 2008 como marco da difusão científica, artística e cultural da Paraíba.',
                'end' => 'Av. João Cirillo Silva, Altiplano Cabo Branco, João Pessoa - PB',
                'tempo' => 150,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1485,
                'lng' => -34.7995,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Jardim Botânico Benjamin Maranhão',
                'desc' => 'Uma das maiores reservas de Mata Atlântica primária em área urbana do Brasil com 515 hectares, trilhas ecológicas guiadas e riachos.',
                'hist' => 'Criado para proteger o ecossistema florestal e as nascentes do Rio Jaguaribe.',
                'end' => 'Av. Dom Pedro II, Torre, João Pessoa - PB',
                'tempo' => 150,
                'acess' => ['deficiencia_auditiva'],
                'lat' => -7.1380,
                'lng' => -34.8610,
                'foto' => 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Parque da Lagoa Solon de Lucena',
                'desc' => 'Cartão-postal no coração da capital rodeado por palmeiras imperiais, espelho d água com fonte luminosa e pista de caminhada.',
                'hist' => 'Antiga Lagoa dos Irerês, urbanizada na década de 1920 e totalmente requalificada como parque público multifuncional.',
                'end' => 'Parque Solon de Lucena, Centro, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1210,
                'lng' => -34.8820,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Parque Zoobotânico Arruda Câmara (Bica)',
                'desc' => 'Oásis ecológico com nascente natural de água mineral cristalina, animais da fauna silvestre, árvores centenárias e trenzinho para crianças.',
                'hist' => 'Fundado em 1922 pelo prefeito Walfredo Guedes Pereira, tombado pelo IPHAEP como patrimônio natural.',
                'end' => 'Av. Gouveia Nóbrega, Roger, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante'],
                'lat' => -7.1105,
                'lng' => -34.8770,
                'foto' => 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Bosque dos Sonhos',
                'desc' => 'Espaço de contemplação arborizado com mirante para a Ponta do Seixas, lojas de souvenir, artesanato em conchas e doces típicos.',
                'hist' => 'Localizado ao lado do Farol do Cabo Branco, ponto de parada obrigatória dos passeios turísticos.',
                'end' => 'Ponta do Seixas, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1472,
                'lng' => -34.7968,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Parque Linear Parahyba (I, II e III)',
                'desc' => 'Moderno parque linear com ciclovia, quadras esportivas, pista de skate, lagos com patos e áreas de convivência no Bessa.',
                'hist' => 'Projeto premiado de requalificação urbana que valorizou a bacia hidrográfica do Bessa e o lazer ao ar livre.',
                'end' => 'Rua Severino Nicolau de Melo, Bessa, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.0780,
                'lng' => -34.8380,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Praça da Independência',
                'desc' => 'Praça comemorativa com o Monumento à Independência em granito e bronze erguido no centro geométrico da capital.',
                'hist' => 'Inaugurada em 1922 no centenário da Independência do Brasil.',
                'end' => 'Av. Epitácio Pessoa com Av. Dom Pedro II, Tambiá, João Pessoa - PB',
                'tempo' => 30,
                'acess' => ['cadeirante'],
                'lat' => -7.1240,
                'lng' => -34.8750,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Espaço Cultural José Lins do Rego',
                'desc' => 'Grandioso complexo com teatro, cinema de arte, planetário, biblioteca pública, galeria de artes plásticas e praça de eventos.',
                'hist' => 'Inaugurado em 1982 e batizado em homenagem ao célebre romancista paraibano autor de Menino de Engenho.',
                'end' => 'Rua Abdias Gomes dos Santos, 800, Tambauzinho, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1265,
                'lng' => -34.8480,
                'foto' => 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Centro de Convenções Poeta Ronaldo Cunha Lima',
                'desc' => 'Um dos maiores e mais modernos centros de eventos do país, com arquitetura arrojada em formato de asa delta e teatro monumental.',
                'hist' => 'Polo do turismo corporativo, feiras internacionais e congressos científicos da América do Sul.',
                'end' => 'Rodovia PB-008, Km 5, Polo Turístico Cabo Branco, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1780,
                'lng' => -34.8210,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Usina Cultural Energisa',
                'desc' => 'Antiga usina termelétrica transformada em centro cultural com cinema, galerias de arte contemporânea, teatro de arena e café.',
                'hist' => 'Marco da arqueologia industrial preservada na Paraíba para difusão artística.',
                'end' => 'R. Juarez Távora, 197, Torre, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1270,
                'lng' => -34.8680,
                'foto' => 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- ARTESANATO, COMPRAS & FEIRAS TÍPICAS ---
            [
                'cat' => $catCultura,
                'nome' => 'Mercado de Artesanato Paraibano (MAP)',
                'desc' => 'Complexo com mais de 200 lojas de renda renascença, bordados de labirinto, cerâmicas, couro, doces de caju e cachaças premiadas da Paraíba.',
                'hist' => 'Principal centro de comercialização e valorização das tradições artesanais do estado.',
                'end' => 'Av. Senador Ruy Carneiro, Tambaú, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1128,
                'lng' => -34.8295,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Feirinha de Artesanato de Tambaú',
                'desc' => 'Feira noturna ao ar livre na orla com roupas de praia, souvenirs, comidas de rua típicas como tapioca recheada, acarajé e castanhas.',
                'hist' => 'Ponto de encontro obrigatório para o passeio noturno dos visitantes na orla.',
                'end' => 'Praça Santo Antônio, Tambaú, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1140,
                'lng' => -34.8235,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Mercado Central de João Pessoa',
                'desc' => 'Mercado tradicional com frutas tropicais (mangaba, umbu, cajá), queijos de coalho e manteiga artesanais, rapaduras e ervas medicinais.',
                'hist' => 'Centro vital de abastecimento popular em funcionamento contínuo há décadas.',
                'end' => 'Av. Dom Pedro II, Centro, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1215,
                'lng' => -34.8790,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Celeiro Espaço Criativo',
                'desc' => 'Espaço municipal dedicado à economia criativa, exposições de mestres artesãos paraibanos, oficinas e vendas de peças autorais.',
                'hist' => 'Criado pela prefeitura de João Pessoa no bairro do Altiplano para impulsionar talentos locais.',
                'end' => 'Av. João Cirillo Silva, Altiplano, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1430,
                'lng' => -34.8110,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- GASTRONOMIA REGIONAL & POLOS GOURMET ---
            [
                'cat' => $catGastronomia,
                'nome' => 'Bar do Cuscuz João Pessoa',
                'desc' => 'Ícone gastronômico paraibano na orla do Cabo Branco, famoso pelas porções generosas de cuscuz recheado, carne de sol e vista para o mar.',
                'hist' => 'Rede de culinária nordestina que começou no interior e virou parada imperdível na orla pessoense.',
                'end' => 'Av. Cabo Branco, 3056, Cabo Branco, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1280,
                'lng' => -34.8215,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Restaurante Tábua de Carne',
                'desc' => 'Especializado na autêntica carne de sol sertaneja servida em tábuas fumegantes com macaxeira frita, paçoca e feijão verde.',
                'hist' => 'Mais de 30 anos de tradição em cortes nobres e receitas clássicas da Paraíba.',
                'end' => 'Av. Sen. Ruy Carneiro, 648, Manaíra, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1090,
                'lng' => -34.8320,
                'foto' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Peixada do Guiomar',
                'desc' => 'Tradicional restaurante de beira-mar famoso pela peixada paraibana com pirão, camarões ensopados e moquecas aromáticas.',
                'hist' => 'Fundado por Dona Guiomar na década de 1970, marco da culinária caiçara pessoense.',
                'end' => 'Av. Ministro José Américo de Almeida, Cabo Branco, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1320,
                'lng' => -34.8205,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Gulliver Restaurante',
                'desc' => 'Alta gastronomia de influência francesa e mediterrânea com frutos do mar nobres, carta de vinhos premiada e ambiente refinado.',
                'hist' => 'Referência em celebrações e jantares requintados na capital.',
                'end' => 'Av. Olinda, 590, Tambaú, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante'],
                'lat' => -7.1110,
                'lng' => -34.8260,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Canyon Coqueirinho Gastronomia',
                'desc' => 'Restaurante premiado em falésias paradisíacas com vista deslumbrante e pratos autorais de camarão no abacaxi e peixes grelhados.',
                'hist' => 'Destino gastronômico de viajantes do mundo todo no litoral paraibano.',
                'end' => 'Praia de Coqueirinho, Costa do Conde / João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['cadeirante'],
                'lat' => -7.3150,
                'lng' => -34.7980,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Vila do Porto Gastronomia e Arte',
                'desc' => 'Restaurante e espaço cultural em casarão histórico com música ao vivo, petiscos autorais e drinks temáticos no Centro Histórico.',
                'hist' => 'Pioneiro na revitalização noturna da Praça São Frei Pedro Gonçalves e Hotel Globo.',
                'end' => 'Praça São Frei Pedro Gonçalves, 8, Varadouro, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1118,
                'lng' => -34.8915,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Adega do Alfredo',
                'desc' => 'Restaurante português tradicional famoso pelos autênticos pratos de bacalhau ao forno, polvo à lagareiro e pastel de nata.',
                'hist' => 'Fundado por imigrantes portugueses há mais de 40 anos em Manaíra.',
                'end' => 'Rua Fernando Luiz Henrique dos Santos, Bessa, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.0850,
                'lng' => -34.8350,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Cervejaria Artesanal Vierbrauer',
                'desc' => 'Microcervejaria local com chopps artesanais autorais (IPA, Weiss, Sour com frutas tropicais) e petiscos de boteco nordestino.',
                'hist' => 'Destaque no circuito de cervejas artesanais premiadas da Paraíba.',
                'end' => 'Av. Flávio Ribeiro Coutinho, Manaíra, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante'],
                'lat' => -7.0950,
                'lng' => -34.8360,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- AVENTURA, TRILHAS, MIRANTES & ESPORTES NÁUTICOS ---
            [
                'cat' => $catAventura,
                'nome' => 'Trilha das Falésias do Cabo Branco',
                'desc' => 'Trilha cênica sobre falésias avermelhadas com vista panorâmica do encontro do oceano atlântico com a floresta de restinga.',
                'hist' => 'Caminho geológico natural de grande relevância geomorfológica paraibana.',
                'end' => 'Acesso pelo Farol do Cabo Branco, João Pessoa - PB',
                'tempo' => 90,
                'acess' => [],
                'lat' => -7.1490,
                'lng' => -34.7955,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAventura,
                'nome' => 'Circuito Náutico de Mergulho Naufrágio Queimado',
                'desc' => 'Ponto de mergulho autônomo sobre o navio a vapor Queimado naufragado em 1878, com vida marinha exuberante como arraias e tartarugas.',
                'hist' => 'Patrimônio arqueológico subaquático protegido da costa de João Pessoa.',
                'end' => 'Saída náutica da Praia de Tambaú, João Pessoa - PB',
                'tempo' => 240,
                'acess' => [],
                'lat' => -7.0800,
                'lng' => -34.7800,
                'foto' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAventura,
                'nome' => 'Passeio de Caiaque e SUP no Rio Sanhauá',
                'desc' => 'Expedição ecológica pelas águas calmas e manguezais do rio onde nasceu a cidade de João Pessoa.',
                'hist' => 'Navegação pelas rotas dos primeiros navegadores do século XVI.',
                'end' => 'Cais do Varadouro / Porto do Capim, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['deficiencia_auditiva'],
                'lat' => -7.1100,
                'lng' => -34.8940,
                'foto' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAventura,
                'nome' => 'Trilha do Parque Ecológico Lauro Pires Xavier',
                'desc' => 'Área verde no Bessa com trilhas sombreadas para caminhada e observação de pássaros da Mata Atlântica.',
                'hist' => 'Reserva ecológica urbana mantida para educação ambiental.',
                'end' => 'Rua Napoleão Duré, Bessa, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.0720,
                'lng' => -34.8360,
                'foto' => 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAventura,
                'nome' => 'Ciclovia da Orla Cabo Branco - Bessa',
                'desc' => 'Mais de 12 km contínuos de ciclovia à beira-mar conectando as praias de Cabo Branco, Tambaú, Manaíra e Bessa com estações de bike compartilhada.',
                'hist' => 'Uma das maiores e mais seguras ciclovias urbanas de praia do Brasil.',
                'end' => 'Orla de João Pessoa (Av. Cabo Branco até Av. Gov. Flávio Ribeiro Coutinho), João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1150,
                'lng' => -34.8230,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- PONTOS ADICIONAIS DA CAPITAL PARAIBANA ---
            [
                'cat' => $catCultura,
                'nome' => 'Casa de José Américo de Almeida',
                'desc' => 'Casa-museu onde viveu o célebre escritor de A Bagaceira e político paraibano, com acervo de manuscritos, biblioteca e jardim à beira-mar.',
                'hist' => 'Fundação cultural tombada que preserva a história literária e política do Brasil republicano.',
                'end' => 'Av. Cabo Branco, 3336, Cabo Branco, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1360,
                'lng' => -34.8185,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Pavilhão do Chá',
                'desc' => 'Monumento histórico de ferro fundido no centro em estilo art nouveau onde a sociedade do início do século XX se reunia para o chá da tarde.',
                'hist' => 'Inaugurado em 1917, hoje espaço revitalizado com apresentações de choro e artesanato.',
                'end' => 'Praça Venâncio Neiva, Centro, João Pessoa - PB',
                'tempo' => 40,
                'acess' => ['cadeirante'],
                'lat' => -7.1180,
                'lng' => -34.8830,
                'foto' => 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Ponte Sanhauá e Porto do Capim',
                'desc' => 'Local histórico onde atracavam as primeiras embarcações portuguesas no século XVI para o comércio do pau-brasil.',
                'hist' => 'Berço geográfico da fundação da cidade de Nossa Senhora das Neves em 1585.',
                'end' => 'Rua do Capim, Varadouro, João Pessoa - PB',
                'tempo' => 45,
                'acess' => [],
                'lat' => -7.1090,
                'lng' => -34.8935,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Praça Rio Branco (Sabadinho Bom)',
                'desc' => 'Praça histórica cercada por casarios coloniais onde acontece todos os sábados o tradicional projeto de chorinho gratuito ao ar livre.',
                'hist' => 'Espaço de consagração da música instrumental e convivência cidadã no Centro Histórico.',
                'end' => 'Praça Rio Branco, Centro, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1165,
                'lng' => -34.8850,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Tribunal de Justiça da Paraíba (Palácio da Justiça)',
                'desc' => 'Edifício monumental com imponentes colunas clássicas e tribunal do júri histórico no centro cívico.',
                'hist' => 'Marco da organização jurídica do estado desde o início do século XX.',
                'end' => 'Praça João Pessoa, Centro, João Pessoa - PB',
                'tempo' => 40,
                'acess' => ['cadeirante'],
                'lat' => -7.1168,
                'lng' => -34.8844,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGrutas,
                'nome' => 'Mirante do Altiplano',
                'desc' => 'Ponto alto no bairro do Altiplano com vista panorâmica espetacular de toda a orla urbana e do Oceano Atlântico.',
                'hist' => 'Região de maior altitude costeira da cidade com brisa constante.',
                'end' => 'Rua Poeta Luiz Raimundo Batista de Carvalho, Altiplano, João Pessoa - PB',
                'tempo' => 45,
                'acess' => ['cadeirante'],
                'lat' => -7.1410,
                'lng' => -34.8100,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Empório Gourmet Manaíra',
                'desc' => 'Boulevard gastronômico moderno reunindo bistrôs, gelaterias italianas, hambúrgueres artesanais e vinhos internacionais.',
                'hist' => 'Polo moderno de gastronomia e encontros sociais noturnos na capital.',
                'end' => 'Av. Edson Ramalho, Manaíra, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1040,
                'lng' => -34.8325,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Sorveteria Tropicalia Tambaú',
                'desc' => 'Sorveteria artesanal famosa por seus sabores autênticos de frutas do Nordeste: mangaba, graviola, tapioca, cajá, siriguela e cupuaçu.',
                'hist' => 'Parada clássica de turistas e moradores após o banho de mar em Tambaú.',
                'end' => 'Av. Almirante Tamandaré, Tambaú, João Pessoa - PB',
                'tempo' => 30,
                'acess' => ['cadeirante'],
                'lat' => -7.1130,
                'lng' => -34.8240,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catHospedagem,
                'nome' => 'Hotel Tambaú (Patrimônio Modernista)',
                'desc' => 'Ícone da arquitetura hoteleira modernista brasileira em formato de disco voador circular construído sobre a areia da praia.',
                'hist' => 'Obra-prima de Sérgio Bernardes inaugurada em 1971, tombada pelo patrimônio histórico e cartão postal mundial.',
                'end' => 'Av. Almirante Tamandaré, 229, Tambaú, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1145,
                'lng' => -34.8225,
                'foto' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- PONTOS TURÍSTICOS E PRAIAS EXPANDIDAS DE JOÃO PESSOA & LITORAL ---
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Camboinha',
                'desc' => 'Praia de mar extremamente calmo e límpido, base dos passeios de lancha e catamarã para o Parque Estadual Marinho de Areia Vermelha.',
                'hist' => 'Área de veraneio nobre com marinas privativas e águas calmas protegidas por arrecifes.',
                'end' => 'Av. Beira Mar, Camboinha, Região Metropolitana de João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['cadeirante'],
                'lat' => -7.0150,
                'lng' => -34.8280,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia do Poço',
                'desc' => 'Tradicional praia de pescadores com mar calmo, areia clara, barracas de peixe frito com macaxeira e travessias náuticas.',
                'hist' => 'Comunidade tradicional pesqueira que mantém o cultivo do camarão e pesca de arrasto artesanal.',
                'end' => 'Rua do Poço, Poço, Região de João Pessoa - PB',
                'tempo' => 150,
                'acess' => ['cadeirante'],
                'lat' => -7.0280,
                'lng' => -34.8310,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Formosa e Dique de Cabedelo',
                'desc' => 'Encontro imponente das águas do Rio Paraíba com o Oceano Atlântico no quebra-mar de pedras do dique com vista para navios cargueiros.',
                'hist' => 'Obra de engenharia marítima do início do século XX para viabilizar o porto de Cabedelo.',
                'end' => 'Praça do Dique, Cabedelo / João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['deficiencia_auditiva'],
                'lat' => -6.9680,
                'lng' => -34.8320,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia do Amor e Pedra Furada',
                'desc' => 'Praia mística com a famosa formação rochosa da Pedra Furada, onde reza a lenda que casais que passam por ela têm amor eterno.',
                'hist' => 'Patrimônio geológico e turístico da Costa do Conde no litoral sul.',
                'end' => 'Praia do Amor, Conde / Litoral Sul de João Pessoa - PB',
                'tempo' => 120,
                'acess' => [],
                'lat' => -7.2900,
                'lng' => -34.7990,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Carapibus (Piscinas Naturais)',
                'desc' => 'Praia paradisíaca com barreira de corais na orla formando piscinas mornas de água transparente na maré baixa.',
                'hist' => 'Uma das praias mais procuradas para hospedagem de charme e descanso no litoral paraibano.',
                'end' => 'Carapibus, Litoral Sul de João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['cadeirante'],
                'lat' => -7.2980,
                'lng' => -34.8010,
                'foto' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Tabatinga e Rio Doce',
                'desc' => 'Praia cinematográfica cercada por falésias multicoloridas e o deságue de lagoas de água doce para banho relaxante de argila medicinal.',
                'hist' => 'Famosa pelas propriedades terapêuticas dos sedimentos minerais das suas falésias.',
                'end' => 'Tabatinga, Costa do Conde / João Pessoa - PB',
                'tempo' => 180,
                'acess' => [],
                'lat' => -7.3050,
                'lng' => -34.7995,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Coqueirinho (Canyon e Mirantes)',
                'desc' => 'Eleita uma das praias mais bonitas do Brasil, com enseada recortada por coqueirais ondulantes, cânions coloridos e mar esmeralda.',
                'hist' => 'Cenário preservado de grande beleza cênica e biodiversidade de restinga.',
                'end' => 'Coqueirinho, Litoral Sul de João Pessoa - PB',
                'tempo' => 240,
                'acess' => ['deficiencia_auditiva'],
                'lat' => -7.3180,
                'lng' => -34.7960,
                'foto' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia de Tambaba e Mirante da Natureza',
                'desc' => 'Primeira praia de naturismo oficial do Nordeste com falésias dramáticas, piscinas naturais esculpidas em pedras e área de preservação.',
                'hist' => 'Reconhecida internacionalmente pelo respeito ao ecossistema e filosofia ambientalista.',
                'end' => 'Tambaba, Costa do Conde / João Pessoa - PB',
                'tempo' => 180,
                'acess' => [],
                'lat' => -7.3550,
                'lng' => -34.7980,
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catAgua,
                'nome' => 'Praia Bela e Estuário do Rio Mucatu',
                'desc' => 'Encontro de um rio límpido de águas mornas com o mar aberto, permitindo passeios de caiaque, tirolesa e quiosques dentro da água.',
                'hist' => 'Polo turístico de ecoturismo e gastronomia à beira da lagoa natural.',
                'end' => 'Praia Bela, Pitimbu / Litoral Sul de João Pessoa - PB',
                'tempo' => 240,
                'acess' => ['cadeirante'],
                'lat' => -7.4200,
                'lng' => -34.8050,
                'foto' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- PATRIMÔNIO CULTURAL & ESPAÇOS ARTÍSTICOS ADICIONAIS ---
            [
                'cat' => $catCultura,
                'nome' => 'Igreja de Nossa Senhora do Rosário dos Pretos',
                'desc' => 'Igreja histórica do século XVII construída pela irmandade de homens negros e escravizados com arquitetura colonial sóbria.',
                'hist' => 'Marco da fé, resistência e ancestralidade afro-brasileira na história de João Pessoa.',
                'end' => 'Rua da Areia, Centro Histórico, João Pessoa - PB',
                'tempo' => 45,
                'acess' => ['cadeirante'],
                'lat' => -7.1125,
                'lng' => -34.8890,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Palácio dos Bispos (Cúria Metropolitana)',
                'desc' => 'Edificação do século XVIII que serviu de residência episcopal e abriga biblioteca eclesiástica com manuscritos coloniais.',
                'hist' => 'Testemunho do poder da Igreja Católica e da expansão urbana colonial na colina do centro.',
                'end' => 'Praça Dom Ulrico, Centro Histórico, João Pessoa - PB',
                'tempo' => 45,
                'acess' => ['cadeirante'],
                'lat' => -7.1145,
                'lng' => -34.8870,
                'foto' => 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Museu da Imagem e do Som da Paraíba (MIS-PB)',
                'desc' => 'Acervo histórico de fotografias raras, fitas cinematográficas, gravações musicais e memórias radiofônicas da Paraíba.',
                'hist' => 'Guardião da história audiovisual e da memória dos artistas paraibanos.',
                'end' => 'Rua Conselheiro Henriques, Centro, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1150,
                'lng' => -34.8855,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Memorial Jackson do Pandeiro',
                'desc' => 'Espaço comemorativo em homenagem ao Rei do Ritmo, Jackson do Pandeiro, com fotos, instrumentos musicais e discografia completa.',
                'hist' => 'Tributo ao maior ritmista da música popular brasileira nascido na Paraíba.',
                'end' => 'Espaço Cultural José Lins do Rego, Tambauzinho, João Pessoa - PB',
                'tempo' => 45,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1260,
                'lng' => -34.8475,
                'foto' => 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Galeria Archidy Picado',
                'desc' => 'Galeria de artes visuais contemporâneas com mostras rotativas de artistas plásticos paraibanos, instalações e esculturas.',
                'hist' => 'Uma das mais prestigiosas galerias públicas de arte do Nordeste.',
                'end' => 'Espaço Cultural José Lins do Rego, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1268,
                'lng' => -34.8482,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Cine Banguê - Cinema de Arte de João Pessoa',
                'desc' => 'Cinema público dedicado à exibição de filmes de arte independentes, mostras de cinema mundial e produções do cinema paraibano.',
                'hist' => 'Referência de formação de público e exibição de cinema autoral desde os anos 1980.',
                'end' => 'Funesc, R. Abdias Gomes dos Santos, Tambauzinho, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.1272,
                'lng' => -34.8478,
                'foto' => 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Praça dos Três Poderes da Paraíba',
                'desc' => 'Esplanada cívica onde se concentram o Palácio da Redenção, a Assembleia Legislativa e o Tribunal de Justiça do Estado.',
                'hist' => 'Centro político do estado cercado por fontes d água e árvores frondosas.',
                'end' => 'Praça João Pessoa, Centro, João Pessoa - PB',
                'tempo' => 30,
                'acess' => ['cadeirante'],
                'lat' => -7.1172,
                'lng' => -34.8838,
                'foto' => 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Fonte dos Milagres de Tambiá',
                'desc' => 'Antiga bica de água natural do século XIX tombada pelo patrimônio, rodeada por jardins históricos no bairro de Tambiá.',
                'hist' => 'Serviu de fonte de água potável para os moradores durante as secas históricas do século passado.',
                'end' => 'Parque Arruda Câmara / Bairro de Tambiá, João Pessoa - PB',
                'tempo' => 30,
                'acess' => [],
                'lat' => -7.1110,
                'lng' => -34.8760,
                'foto' => 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Beco dos Sapateiros & Casarões Antigos',
                'desc' => 'Ruela histórica de paralelepípedos ladeada por oficinas tradicionais de couro e casarios coloniais recuperados no Varadouro.',
                'hist' => 'Passagem de comércio de calçados artesanais desde o século XIX.',
                'end' => 'Varadouro, Centro Histórico, João Pessoa - PB',
                'tempo' => 30,
                'acess' => [],
                'lat' => -7.1130,
                'lng' => -34.8905,
                'foto' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catCultura,
                'nome' => 'Memorial Augusto dos Anjos',
                'desc' => 'Memorial e monumento dedicado ao grande poeta paraibano do pré-modernismo, autor da célebre obra Eu.',
                'hist' => 'Espaço cultural com manuscritos poéticos e busto do poeta do século XX.',
                'end' => 'Parque Arruda Câmara, João Pessoa - PB',
                'tempo' => 30,
                'acess' => ['cadeirante'],
                'lat' => -7.1098,
                'lng' => -34.8765,
                'foto' => 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
            ],

            // --- GASTRONOMIA ADICIONAL DE JOÃO PESSOA ---
            [
                'cat' => $catGastronomia,
                'nome' => 'Lovina Beach Bar & Restaurante',
                'desc' => 'Beach club de alta gastronomia à beira-mar com petiscos sofisticados de frutos do mar, música lounge ao vivo e gazebos de praia.',
                'hist' => 'Ponto de encontro da moda e turismo jovem em frente ao mar da Paraíba.',
                'end' => 'Av. Vitorino Cardoso, Ponta de Campina / Cabedelo - João Pessoa - PB',
                'tempo' => 180,
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
                'lat' => -7.0200,
                'lng' => -34.8290,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Restaurante Camarão Imperial Tambaú',
                'desc' => 'Especializado em rodízio e pratos executivos de camarões com mais de 20 variações de molhos e queijos nordestinos.',
                'hist' => 'Ponto tradicional da avenida gastronômica de Tambaú.',
                'end' => 'Av. Almirante Tamandaré, 400, Tambaú, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1135,
                'lng' => -34.8230,
                'foto' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Quiosque Olho de Lula',
                'desc' => 'O mais famoso quiosque de frutos do mar do calçadão de Cabo Branco, servindo lula à dore, caranguejo cozido e cervejas estupidamente geladas.',
                'hist' => 'Patrimônio da boemia e da cultura praiana pessoense desde os anos 1980.',
                'end' => 'Av. Cabo Branco, 2300, Cabo Branco, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante'],
                'lat' => -7.1260,
                'lng' => -34.8210,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Restaurante Cozinha Roccia (Chef Onildo Rocha)',
                'desc' => 'Restaurante de alta gastronomia brasileira autoral que resgata ingredientes do sertão paraibano com técnicas internacionais inovadoras.',
                'hist' => 'Premiado nacionalmente como expoente da gastronomia nordestina contemporânea.',
                'end' => 'Rua Antônio Rabelo Júnior, 170, Tambauzinho, João Pessoa - PB',
                'tempo' => 120,
                'acess' => ['cadeirante'],
                'lat' => -7.1245,
                'lng' => -34.8380,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Sonho Doce Café e Doceria Tradicional',
                'desc' => 'Elegante café e doceria em casarão com jardim de inverno servindo tortas nobres, doces de frutas nordestinas e salgados finos.',
                'hist' => 'Mais de 30 anos de referência em confeitaria fina e chás da tarde na cidade.',
                'end' => 'Praça da Independência, Tambiá, João Pessoa - PB',
                'tempo' => 60,
                'acess' => ['cadeirante'],
                'lat' => -7.1238,
                'lng' => -34.8745,
                'foto' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'Churrascaria Tererê Orla',
                'desc' => 'Tradicional rodízio de carnes nobres com buffet farto de saladas, sushis e frutos do mar com vista direta para a Praia de Cabo Branco.',
                'hist' => 'Uma das mais antigas e premiadas churrascarias da orla paraibana.',
                'end' => 'Av. Cabo Branco, 1830, Cabo Branco, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.1240,
                'lng' => -34.8218,
                'foto' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'cat' => $catGastronomia,
                'nome' => 'República dos Camarões Bessa',
                'desc' => 'Restaurante familiar à beira-mar com diversas opções de moquecas paraibanas, casquinha de siri e peixe grelhado.',
                'hist' => 'Ponto de parada querido por quem desfruta das águas tranquilas do Caribessa.',
                'end' => 'Av. Artur Monteiro de Paiva, Bessa, João Pessoa - PB',
                'tempo' => 90,
                'acess' => ['cadeirante'],
                'lat' => -7.0690,
                'lng' => -34.8295,
                'foto' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
            ]
        ];

        // 4. Inserir Atrativos no Banco
        $totalAtrativos = 0;
        foreach ($atrativos as $data) {
            $atrativo = Atrativo::firstOrCreate(
                [
                    'nome' => $data['nome'],
                    'municipio_id' => $municipio->id
                ],
                [
                    'categoria_id' => $data['cat']->id,
                    'descricao' => $data['desc'],
                    'historia' => $data['hist'],
                    'endereco' => $data['end'],
                    'lat' => $data['lat'],
                    'lng' => $data['lng'],
                    'tempo_medio_visita' => $data['tempo'],
                    'status' => 'ativo',
                    'acessibilidade' => $data['acess'],
                    'validado_por' => $admin ? $admin->id : null,
                    'validado_em' => now(),
                ]
            );

            // Mídia / Foto
            if (!empty($data['foto'])) {
                Midia::firstOrCreate(
                    [
                        'entidade_type' => Atrativo::class,
                        'entidade_id' => $atrativo->id,
                        'tipo' => 'foto'
                    ],
                    [
                        'url' => $data['foto'],
                        'alt_text' => 'Foto de ' . $atrativo->nome,
                        'autor' => 'Acervo Oficial Turismo João Pessoa & Wikimedia',
                        'licenca' => 'CC-BY-SA',
                    ]
                );
            }

            // QR Code Oficial
            QrCode::firstOrCreate(
                ['atrativo_id' => $atrativo->id],
                ['hash_code' => Str::random(10)]
            );

            $totalAtrativos++;
        }

        // 5. Catálogo Extensivo de Eventos de João Pessoa (30 Eventos)
        $eventos = [
            [
                'nome' => 'São João de João Pessoa — Polo Busto de Tamandaré',
                'desc' => 'Grandes shows com os principais nomes do forró e música regional, apresentações de quadrilhas juninas e gastronomia típica no palco da orla.',
                'local' => 'Busto de Tamandaré, Praia de Cabo Branco / Tambaú',
                'inicio' => now()->addMonths(2)->setDay(20)->setTime(19, 0),
                'fim' => now()->addMonths(2)->setDay(24)->setTime(3, 0),
                'gratuito' => true,
                'organizador' => 'Prefeitura Municipal de João Pessoa / FUNJOPE',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Festival Folia de Rua — Bloco Muriçocas do Miramar',
                'desc' => 'A maior prévia carnavalesca do país na quarta-feira que antecede o carnaval, reunindo mais de 400 mil foliões pela Avenida Epitácio Pessoa.',
                'local' => 'Av. Presidente Epitácio Pessoa (Via Folia), João Pessoa - PB',
                'inicio' => now()->addMonths(6)->setDay(15)->setTime(20, 0),
                'fim' => now()->addMonths(6)->setDay(16)->setTime(5, 0),
                'gratuito' => true,
                'organizador' => 'Associação dos Blocos do Folia de Rua',
                'faixa' => '16+',
                'acess' => ['deficiencia_auditiva'],
            ],
            [
                'nome' => 'Salão do Artesanato Paraibano — Edição Verão',
                'desc' => 'A maior feira de artesanato e economia criativa da Paraíba com homenagens a mestres artesãos, renda renascença e delícias regionais.',
                'local' => 'Espaço Cultural José Lins do Rego / Orla de Tambaú',
                'inicio' => now()->addDays(10)->setTime(15, 0),
                'fim' => now()->addDays(30)->setTime(22, 0),
                'gratuito' => true,
                'organizador' => 'Governo do Estado da Paraíba / PAP',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Fest Aruanda do Cinema Brasileiro',
                'desc' => 'Festival audiovisual histórico com exibição de longas e curtas-metragens nacionais, debates com diretores consagrados e oficinas gratuitas.',
                'local' => 'Cinépolis Manaíra Shopping / Sala Rômulo Araújo',
                'inicio' => now()->addMonths(3)->setDay(5)->setTime(14, 0),
                'fim' => now()->addMonths(3)->setDay(11)->setTime(23, 0),
                'gratuito' => true,
                'organizador' => 'UFPB e Comitê Fest Aruanda',
                'faixa' => '14+',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Sabadinho Bom no Centro Histórico',
                'desc' => 'Encontro musical semanal de chorinho e samba de raiz na Praça Rio Branco com mesas ao ar livre e gastronomia tradicional.',
                'local' => 'Praça Rio Branco, Centro Histórico, João Pessoa - PB',
                'inicio' => now()->next('Saturday')->setTime(12, 0),
                'fim' => now()->next('Saturday')->setTime(16, 30),
                'gratuito' => true,
                'organizador' => 'FUNJOPE - Fundação Cultural de João Pessoa',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Festival Forró Fest Paraíba',
                'desc' => 'Competição de música nordestina e shows com mestres sanfoneiros valorizando as raízes do xote, baião e arrasta-pé.',
                'local' => 'Parque Solon de Lucena (Lagoa), Centro, João Pessoa - PB',
                'inicio' => now()->addMonths(1)->setDay(18)->setTime(18, 0),
                'fim' => now()->addMonths(1)->setDay(20)->setTime(23, 59),
                'gratuito' => true,
                'organizador' => 'Rede Paraíba de Comunicação',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Festa das Neves — Padroeira da Paraíba',
                'desc' => 'Comemoração dos 440 anos da fundação de João Pessoa com parque de diversões na Lagoa, missas solenes e shows na praça da Catedral.',
                'local' => 'Centro Histórico e Parque Solon de Lucena',
                'inicio' => now()->addMonths(4)->setDay(1)->setTime(17, 0),
                'fim' => now()->addMonths(4)->setDay(5)->setTime(23, 59),
                'gratuito' => true,
                'organizador' => 'Arquidiocese da Paraíba & Prefeitura de João Pessoa',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Festival Gastronômico Estações Sabores PB',
                'desc' => 'Circuito gastronômico com menus exclusivos de frutos do mar e culinária sertaneja a preços promocionais em 40 restaurantes da capital.',
                'local' => 'Restaurantes participantes em Tambaú, Manaíra, Cabo Branco e Bessa',
                'inicio' => now()->addDays(15)->setTime(11, 30),
                'fim' => now()->addDays(45)->setTime(23, 0),
                'gratuito' => false,
                'organizador' => 'Abrasel Paraíba',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Meia Maratona Internacional de João Pessoa',
                'desc' => 'Corrida de rua oficial com percursos de 5km, 10km e 21km ao longo de toda a deslumbrante orla marítima ao nascer do sol.',
                'local' => 'Largada no Busto de Tamandaré, Praia de Cabo Branco',
                'inicio' => now()->addMonths(5)->setDay(10)->setTime(5, 30),
                'fim' => now()->addMonths(5)->setDay(10)->setTime(10, 0),
                'gratuito' => false,
                'organizador' => 'Federação Paraibana de Atletismo',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Festival Internacional de Música Clássica de João Pessoa',
                'desc' => 'Concertos sinfônicos com solistas internacionais e orquestras nas igrejas históricas barrocas do Centro Histórico.',
                'local' => 'Igreja de São Francisco e Mosteiro de São Bento',
                'inicio' => now()->addMonths(7)->setDay(1)->setTime(16, 0),
                'fim' => now()->addMonths(7)->setDay(7)->setTime(21, 0),
                'gratuito' => true,
                'organizador' => 'Prefeitura de João Pessoa & Ministério da Cultura',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Festival de Quadrilhas Juninas de João Pessoa',
                'desc' => 'Espetacular concurso de quadrilhas juninas tradicionais e estilizadas com figurinos suntuosos, coreografias e temas culturais.',
                'local' => 'Arena dos Povos da Praia, Bessa / Orla',
                'inicio' => now()->addMonths(2)->setDay(10)->setTime(19, 0),
                'fim' => now()->addMonths(2)->setDay(16)->setTime(0, 0),
                'gratuito' => true,
                'organizador' => 'Liga das Quadrilhas Juninas de João Pessoa',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Réveillon da Paz de João Pessoa',
                'desc' => 'Mega espetáculo de queima de fogos silenciosos na orla com grandes atrações da MPB e do axé celebrando a chegada do novo ano.',
                'local' => 'Orla de Tambaú e Cabo Branco',
                'inicio' => now()->endOfYear()->setTime(20, 0),
                'fim' => now()->endOfYear()->addDay()->setTime(4, 0),
                'gratuito' => true,
                'organizador' => 'Prefeitura Municipal de João Pessoa',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Feira Literária da Paraíba (FLIPAQ)',
                'desc' => 'Encontro de autores nacionais, lançamentos de livros, saraus poéticos de cordel, contação de histórias e feira de livros com descontos.',
                'local' => 'Estação Cabo Branco - Ciência, Cultura e Artes',
                'inicio' => now()->addMonths(4)->setDay(15)->setTime(9, 0),
                'fim' => now()->addMonths(4)->setDay(19)->setTime(20, 0),
                'gratuito' => true,
                'organizador' => 'Secretaria de Educação e Cultura de João Pessoa',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ],
            [
                'nome' => 'Festival Halleluya João Pessoa',
                'desc' => 'Festival de música cristã, shows com bandas nacionais, tendas temáticas e ações solidárias na praia de Tambaú.',
                'local' => 'Busto de Tamandaré, Tambaú, João Pessoa - PB',
                'inicio' => now()->addMonths(8)->setDay(10)->setTime(18, 0),
                'fim' => now()->addMonths(8)->setDay(12)->setTime(23, 0),
                'gratuito' => true,
                'organizador' => 'Comunidade Católica Shalom',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Feira Nordestina de Moda e Calçados de João Pessoa',
                'desc' => 'A maior feira de vestuário e calçados do estado com desfiles de estilistas locais e marcas regionais.',
                'local' => 'Centro de Convenções Poeta Ronaldo Cunha Lima',
                'inicio' => now()->addMonths(3)->setDay(1)->setTime(10, 0),
                'fim' => now()->addMonths(3)->setDay(4)->setTime(21, 0),
                'gratuito' => false,
                'organizador' => 'Sindicato da Indústria do Vestuário da PB',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Festival de Pipas da Orla de Cabo Branco',
                'desc' => 'Cores e acrobacias no céu com pipas gigantes, oficinas infantis de confecção de pipas e campeonato de manobras.',
                'local' => 'Praia de Cabo Branco (próximo ao Farol)',
                'inicio' => now()->addDays(28)->setTime(14, 0),
                'fim' => now()->addDays(28)->setTime(18, 0),
                'gratuito' => true,
                'organizador' => 'Secretaria de Juventude, Esporte e Recreação',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Circuito Paraibano de Vôlei de Praia',
                'desc' => 'Etapa oficial do circuito estadual com as melhores duplas de vôlei de praia do Brasil na arena montada na areia de Tambaú.',
                'local' => 'Arena de Praia de Tambaú, João Pessoa - PB',
                'inicio' => now()->addMonths(1)->setDay(22)->setTime(8, 0),
                'fim' => now()->addMonths(1)->setDay(24)->setTime(18, 0),
                'gratuito' => true,
                'organizador' => 'Federação Paraibana de Voleibol',
                'faixa' => 'Livre',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Festival de Cervejas Artesanais da Paraíba',
                'desc' => 'Encontro de mais de 20 cervejarias artesanais paraibanas com degustações, gastronomia de rua e shows de rock e blues.',
                'local' => 'Usina Cultural Energisa, Torre, João Pessoa - PB',
                'inicio' => now()->addMonths(4)->setDay(28)->setTime(17, 0),
                'fim' => now()->addMonths(4)->setDay(30)->setTime(23, 59),
                'gratuito' => true,
                'organizador' => 'AcervA Paraibana',
                'faixa' => '18+',
                'acess' => ['cadeirante'],
            ],
            [
                'nome' => 'Romaria de Nossa Senhora da Penha',
                'desc' => 'A maior manifestação de fé da Paraíba, onde mais de 500 mil peregrinos caminham 14 km da Igreja de Lourdes até o Santuário da Penha.',
                'local' => 'Saída da Av. João Machado até a Praia da Penha',
                'inicio' => now()->addMonths(7)->setDay(22)->setTime(21, 0),
                'fim' => now()->addMonths(7)->setDay(23)->setTime(6, 0),
                'gratuito' => true,
                'organizador' => 'Santuário de Nossa Senhora da Penha',
                'faixa' => 'Livre',
                'acess' => ['deficiencia_auditiva'],
            ],
            [
                'nome' => 'Auto de Natal na Praça do Povo',
                'desc' => 'Grandioso espetáculo cênico e coral natalino iluminado contando o nascimento de Jesus com elementos da cultura popular nordestina.',
                'local' => 'Praça do Povo, Espaço Cultural José Lins do Rego',
                'inicio' => now()->addMonths(8)->setDay(20)->setTime(19, 30),
                'fim' => now()->addMonths(8)->setDay(23)->setTime(21, 30),
                'gratuito' => true,
                'organizador' => 'Funesc Paraíba',
                'faixa' => 'Livre',
                'acess' => ['cadeirante', 'deficiencia_auditiva'],
            ]
        ];

        $totalEventos = 0;
        foreach ($eventos as $ev) {
            Evento::firstOrCreate(
                ['nome' => $ev['nome']],
                [
                    'descricao' => $ev['desc'],
                    'local' => $ev['local'],
                    'inicio' => $ev['inicio'],
                    'fim' => $ev['fim'],
                    'gratuito' => $ev['gratuito'],
                    'organizador' => $ev['organizador'],
                    'faixa_etaria' => $ev['faixa'],
                    'acessibilidade' => $ev['acess'],
                    'status' => 'ativo',
                ]
            );
            $totalEventos++;
        }
    }
}
