services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - postgres
      - redis

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE:-destino_inteligente}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-postgres}'
    volumes:
      - 'destino_inteligente_pgsql:/var/lib/postgresql/data'
      - './docker/postgres/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
      - './docker/postgres/extensions.sql:/docker-entrypoint-initdb.d/20-extensions.sql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE:-destino_inteligente}'
        - '-U'
        - '${DB_USERNAME:-postgres}'
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '6381:6379'
    volumes:
      - 'destino_inteligente_redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  destino_inteligente_pgsql:
    driver: local
  destino_inteligente_redis:
    driver: local
