/**
 * Catálogo Central de Cidades, Atrativos e Roteiros Turísticos
 * Utilizado de forma compartilhada na Home, no Mapa e no Seletor de Cidades.
 */

export const CITIES_DATA = [
    {
        name: 'João Pessoa',
        uf: 'PB',
        display: 'João Pessoa PB',
        stateName: 'Paraíba',
        lat: -7.1153,
        lng: -34.8641,
        color: '#005f73',
        badgeClass: 'bg-primary',
        description: 'Capital paraibana com belas praias de águas mornas, piscinas naturais e centro histórico colonial.'
    },
    {
        name: 'Bonito',
        uf: 'MS',
        display: 'Bonito MS',
        stateName: 'Mato Grosso do Sul',
        lat: -21.1275,
        lng: -56.4831,
        color: '#0a9396',
        badgeClass: 'bg-success',
        description: 'Capital do ecoturismo no Brasil, famosa pelas águas ultra transparentes, cavernas e cachoeiras.'
    },
    {
        name: 'Recife',
        uf: 'PE',
        display: 'Recife PE',
        stateName: 'Pernambuco',
        lat: -8.0476,
        lng: -34.8770,
        color: '#ee9b00',
        badgeClass: 'bg-warning',
        description: 'A Veneza brasileira, rica em cultura, frevo, gastronomia e história colonial conectada a Olinda.'
    },
    {
        name: 'Natal',
        uf: 'RN',
        display: 'Natal RN',
        stateName: 'Rio Grande do Norte',
        lat: -5.7945,
        lng: -35.2110,
        color: '#0077b6',
        badgeClass: 'bg-info',
        description: 'A Cidade do Sol, com dunas imponentes, passeios de buggy, praias paradisíacas e o Forte dos Reis Magos.'
    },
    {
        name: 'São Paulo',
        uf: 'SP',
        display: 'São Paulo SP',
        stateName: 'São Paulo',
        lat: -23.5505,
        lng: -46.6333,
        color: '#9b2226',
        badgeClass: 'bg-danger',
        description: 'Metrópole global com museus renomados, vida noturna agitada e gastronomia de classe mundial.'
    }
];

export const PLACES_DATA = [
    // --- JOÃO PESSOA (PB) ---
    {
        id: 101,
        nome: 'Praia de Tambaú',
        cidade: 'João Pessoa',
        uf: 'PB',
        cat: 'Praias & Rios',
        catKey: 'praia',
        catIcon: 'bi-water',
        color: '#0077b6',
        lat: -7.1147,
        lng: -34.8239,
        tempoVisita: '3 horas',
        tempoMinutos: 180,
        rating: 4.9,
        numAvaliacoes: 428,
        endereco: 'Av. Almirante Tamandaré, Tambaú, João Pessoa - PB',
        descricao: 'Uma das praias urbanas mais famosas de João Pessoa, com calçadão movimentado, feirinha de artesanato e saída de passeios de catamarã para Picãozinho.',
        img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante', 'deficiencia_auditiva']
    },
    {
        id: 102,
        nome: 'Farol do Cabo Branco',
        cidade: 'João Pessoa',
        uf: 'PB',
        cat: 'Monumentos & Natureza',
        catKey: 'natureza',
        catIcon: 'bi-geo-alt-fill',
        color: '#ee9b00',
        lat: -7.1477,
        lng: -34.7963,
        tempoVisita: '1 hora',
        tempoMinutos: 60,
        rating: 4.8,
        numAvaliacoes: 310,
        endereco: 'Ponta do Seixas, Cabo Branco, João Pessoa - PB',
        descricao: 'O ponto mais oriental das Américas continentais onde o sol nasce primeiro. Vista panorâmica espetacular do oceano e falésias.',
        img: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante']
    },
    {
        id: 103,
        nome: 'Piscinas Naturais dos Seixas',
        cidade: 'João Pessoa',
        uf: 'PB',
        cat: 'Praias & Rios',
        catKey: 'praia',
        catIcon: 'bi-water',
        color: '#0077b6',
        lat: -7.1597,
        lng: -34.7877,
        tempoVisita: '2h 30min',
        tempoMinutos: 150,
        rating: 4.9,
        numAvaliacoes: 285,
        endereco: 'Praia dos Seixas, João Pessoa - PB',
        descricao: 'Aquários naturais formados por recifes de corais na maré baixa com águas cristalinas repletas de peixes coloridos, ideal para mergulho livre.',
        img: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        destaque: false,
        acessibilidade: ['deficiencia_auditiva']
    },
    {
        id: 104,
        nome: 'Centro Cultural São Francisco',
        cidade: 'João Pessoa',
        uf: 'PB',
        cat: 'Cultura & História',
        catKey: 'cultura',
        catIcon: 'bi-bank',
        color: '#9b2226',
        lat: -7.1155,
        lng: -34.8864,
        tempoVisita: '1h 30min',
        tempoMinutos: 90,
        rating: 4.9,
        numAvaliacoes: 198,
        endereco: 'Praça São Francisco, Centro Histórico, João Pessoa - PB',
        descricao: 'Um dos mais importantes complexos barrocos do Brasil, com igreja, convento, claustro com azulejaria portuguesa e rico acervo sacro.',
        img: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante']
    },
    {
        id: 105,
        nome: 'Mangai João Pessoa',
        cidade: 'João Pessoa',
        uf: 'PB',
        cat: 'Gastronomia Regional',
        catKey: 'gastronomia',
        catIcon: 'bi-cup-hot',
        color: '#2a9d8f',
        lat: -7.1067,
        lng: -34.8315,
        tempoVisita: '1h 30min',
        tempoMinutos: 90,
        rating: 4.9,
        numAvaliacoes: 520,
        endereco: 'Av. Edson Ramalho, 696, Manaíra, João Pessoa - PB',
        descricao: 'Referência nacional em culinária nordestina, buffet rico com carne de sol na nata, baião de dois, tapiocas e doces tradicionais.',
        img: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        destaque: false,
        acessibilidade: ['cadeirante', 'deficiencia_auditiva']
    },
    {
        id: 106,
        nome: 'Nau Frutos do Mar',
        cidade: 'João Pessoa',
        uf: 'PB',
        cat: 'Gastronomia Regional',
        catKey: 'gastronomia',
        catIcon: 'bi-cup-hot',
        color: '#2a9d8f',
        lat: -7.1189,
        lng: -34.8302,
        tempoVisita: '1h 30min',
        tempoMinutos: 90,
        rating: 4.8,
        numAvaliacoes: 440,
        endereco: 'R. Lupércio Branco, 130, Manaíra, João Pessoa - PB',
        descricao: 'Restaurante contemporâneo especializado em frutos do mar com camarões, peixes nobres e ambiente arquitetônico premiado.',
        img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
        destaque: false,
        acessibilidade: ['cadeirante']
    },

    // --- BONITO (MS) ---
    {
        id: 1,
        nome: 'Flutuação no Rio Sucuri',
        cidade: 'Bonito',
        uf: 'MS',
        cat: 'Praias & Rios',
        catKey: 'praia',
        catIcon: 'bi-water',
        color: '#0077b6',
        lat: -21.2642,
        lng: -56.5516,
        tempoVisita: '2 horas',
        tempoMinutos: 120,
        rating: 4.9,
        numAvaliacoes: 612,
        endereco: 'Fazenda São Geraldo, Rodovia Bonito - São Geraldo, Bonito - MS',
        descricao: 'Uma das águas mais cristalinas do mundo. Flutuação suave em meio a cardumes de peixes coloridos e vegetação subaquática exuberante.',
        img: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante', 'deficiencia_auditiva']
    },
    {
        id: 2,
        nome: 'Gruta do Lago Azul',
        cidade: 'Bonito',
        uf: 'MS',
        cat: 'Monumentos & Natureza',
        catKey: 'natureza',
        catIcon: 'bi-geo-alt-fill',
        color: '#ee9b00',
        lat: -21.1469,
        lng: -56.5861,
        tempoVisita: '1h 30min',
        tempoMinutos: 90,
        rating: 4.8,
        numAvaliacoes: 489,
        endereco: 'Rodovia MS 382, Km 20, Bonito - MS',
        descricao: 'Cartão-postal de Bonito, uma caverna impressionante com estalactites e um lago subterrâneo de coloração azul turquesa viva e mágica.',
        img: 'https://images.unsplash.com/photo-1499244571948-7cc805602889?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: []
    },
    {
        id: 3,
        nome: 'Bóia Cross no Rio Formoso',
        cidade: 'Bonito',
        uf: 'MS',
        cat: 'Aventura & Trilhas',
        catKey: 'natureza',
        catIcon: 'bi-bicycle',
        color: '#0a9396',
        lat: -21.1895,
        lng: -56.4523,
        tempoVisita: '1 hora',
        tempoMinutos: 60,
        rating: 4.7,
        numAvaliacoes: 320,
        endereco: 'Parque Ecológico Rio Formoso, Bonito - MS',
        descricao: 'Aventura refrescante em bóias individuais descendo corredeiras e pequenas cachoeiras cercadas por mata ciliar preservada.',
        img: 'https://images.unsplash.com/photo-1533230491024-e22d9976da28?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['deficiencia_auditiva']
    },
    {
        id: 4,
        nome: 'Casa do João',
        cidade: 'Bonito',
        uf: 'MS',
        cat: 'Gastronomia Regional',
        catKey: 'gastronomia',
        catIcon: 'bi-cup-hot',
        color: '#2a9d8f',
        lat: -21.1275,
        lng: -56.4831,
        tempoVisita: '2 horas',
        tempoMinutos: 120,
        rating: 4.9,
        numAvaliacoes: 580,
        endereco: 'Rua Cel. Nélson Felício dos Santos, Centro, Bonito - MS',
        descricao: 'Restaurante acolhedor e famoso pelos peixes da região pantaneira como a Traíra sem espinha, Piraputanga e Pintado na brasa.',
        img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
        destaque: false,
        acessibilidade: ['cadeirante', 'deficiencia_visual']
    },

    // --- RECIFE (PE) ---
    {
        id: 201,
        nome: 'Marco Zero & Recife Antigo',
        cidade: 'Recife',
        uf: 'PE',
        cat: 'Cultura & História',
        catKey: 'cultura',
        catIcon: 'bi-bank',
        color: '#9b2226',
        lat: -8.0631,
        lng: -34.8711,
        tempoVisita: '2 horas',
        tempoMinutos: 120,
        rating: 4.8,
        numAvaliacoes: 410,
        endereco: 'Praça Rio Branco, Bairro do Recife, Recife - PE',
        descricao: 'Coração histórico da capital pernambucana, com vista para o Parque das Esculturas de Brennand, armazéns gastronômicos e feiras de artesanato.',
        img: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante']
    },
    {
        id: 202,
        nome: 'Praia de Boa Viagem',
        cidade: 'Recife',
        uf: 'PE',
        cat: 'Praias & Rios',
        catKey: 'praia',
        catIcon: 'bi-water',
        color: '#0077b6',
        lat: -8.1284,
        lng: -34.9015,
        tempoVisita: '3 horas',
        tempoMinutos: 180,
        rating: 4.7,
        numAvaliacoes: 530,
        endereco: 'Av. Boa Viagem, Recife - PE',
        descricao: 'Praia urbana famosa com orla estruturada, piscinas naturais formadas por arrecifes na maré baixa e coqueirais.',
        img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante']
    },
    {
        id: 203,
        nome: 'Instituto Ricardo Brennand',
        cidade: 'Recife',
        uf: 'PE',
        cat: 'Cultura & História',
        catKey: 'cultura',
        catIcon: 'bi-bank',
        color: '#9b2226',
        lat: -8.0653,
        lng: -34.9642,
        tempoVisita: '2h 30min',
        tempoMinutos: 150,
        rating: 4.9,
        numAvaliacoes: 670,
        endereco: 'Alameda Bernardo Vieira de Melo, Várzea, Recife - PE',
        descricao: 'Castelo medieval que abriga uma das maiores coleções de armas brancas do mundo e acervo monumental sobre o Brasil Holandês.',
        img: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante', 'deficiencia_auditiva']
    },

    // --- NATAL (RN) ---
    {
        id: 301,
        nome: 'Dunas de Genipabu',
        cidade: 'Natal',
        uf: 'RN',
        cat: 'Aventura & Trilhas',
        catKey: 'natureza',
        catIcon: 'bi-bicycle',
        color: '#0a9396',
        lat: -5.7056,
        lng: -35.2012,
        tempoVisita: '3 horas',
        tempoMinutos: 180,
        rating: 4.9,
        numAvaliacoes: 720,
        endereco: 'Extremoz / Litoral Norte, Natal - RN',
        descricao: 'Parque de dunas móveis internacionalmente famoso pelos passeios de buggy "com ou sem emoção", lagoas de água doce e esquibunda.',
        img: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['deficiencia_auditiva']
    },
    {
        id: 302,
        nome: 'Praia de Ponta Negra & Morro do Careca',
        cidade: 'Natal',
        uf: 'RN',
        cat: 'Praias & Rios',
        catKey: 'praia',
        catIcon: 'bi-water',
        color: '#0077b6',
        lat: -5.8752,
        lng: -35.1764,
        tempoVisita: '3 horas',
        tempoMinutos: 180,
        rating: 4.8,
        numAvaliacoes: 640,
        endereco: 'Av. Erivan França, Ponta Negra, Natal - RN',
        descricao: 'A praia mais famosa de Natal com vista privilegiada para a gigantesca duna de preservação do Morro do Careca e orla cheia de quiosques.',
        img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante']
    },
    {
        id: 303,
        nome: 'Forte dos Reis Magos',
        cidade: 'Natal',
        uf: 'RN',
        cat: 'Cultura & História',
        catKey: 'cultura',
        catIcon: 'bi-bank',
        color: '#9b2226',
        lat: -5.7567,
        lng: -35.1947,
        tempoVisita: '1h 30min',
        tempoMinutos: 90,
        rating: 4.7,
        numAvaliacoes: 380,
        endereco: 'Praia do Forte, Natal - RN',
        descricao: 'Fortaleza histórica em formato de estrela construída pelos colonizadores portugueses em 1598 na foz do Rio Potengi.',
        img: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=600&q=80',
        destaque: false,
        acessibilidade: ['cadeirante']
    },

    // --- SÃO PAULO (SP) ---
    {
        id: 401,
        nome: 'Avenida Paulista & MASP',
        cidade: 'São Paulo',
        uf: 'SP',
        cat: 'Cultura & História',
        catKey: 'cultura',
        catIcon: 'bi-bank',
        color: '#9b2226',
        lat: -23.5615,
        lng: -46.6559,
        tempoVisita: '3 horas',
        tempoMinutos: 180,
        rating: 4.9,
        numAvaliacoes: 890,
        endereco: 'Av. Paulista, 1578, Bela Vista, São Paulo - SP',
        descricao: 'A via mais emblemática do país abrigando o MASP com seu icônico vão livre de Lina Bo Bardi, centros culturais e feiras de arte.',
        img: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante', 'deficiencia_visual', 'deficiencia_auditiva']
    },
    {
        id: 402,
        nome: 'Parque Ibirapuera',
        cidade: 'São Paulo',
        uf: 'SP',
        cat: 'Monumentos & Natureza',
        catKey: 'natureza',
        catIcon: 'bi-geo-alt-fill',
        color: '#ee9b00',
        lat: -23.5874,
        lng: -46.6576,
        tempoVisita: '3 horas',
        tempoMinutos: 180,
        rating: 4.8,
        numAvaliacoes: 950,
        endereco: 'Av. Pedro Álvares Cabral, Vila Mariana, São Paulo - SP',
        descricao: 'O pulmão verde de São Paulo projetado por Niemeyer e Burle Marx com lagos, ciclovias, museus e amplas áreas de lazer.',
        img: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
        destaque: true,
        acessibilidade: ['cadeirante']
    },
    {
        id: 403,
        nome: 'Beco do Batman & Vila Madalena',
        cidade: 'São Paulo',
        uf: 'SP',
        cat: 'Cultura & Gastronomia',
        catKey: 'cultura',
        catIcon: 'bi-cup-hot',
        color: '#2a9d8f',
        lat: -23.5570,
        lng: -46.6865,
        tempoVisita: '2 horas',
        tempoMinutos: 120,
        rating: 4.7,
        numAvaliacoes: 510,
        endereco: 'Rua Gonçalo Afonso, Vila Madalena, São Paulo - SP',
        descricao: 'Galeria a céu aberto de grafites vibrantes no bairro boêmio da Vila Madalena, cercada por cafés, ateliês e bares.',
        img: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=600&q=80',
        destaque: false,
        acessibilidade: []
    }
];

export const ROTEIROS_DATA = {
    'João Pessoa': [
        {
            id: 101,
            titulo: 'Praias, Piscinas & Farol',
            subtitulo: 'Orla de Tambaú, piscinas naturais dos Seixas e pôr do sol no Farol.',
            duracao: '1 Dia',
            tag: 'Top Escolha',
            tagColor: 'text-primary',
            badgeBg: 'bg-primary',
            cidade: 'João Pessoa',
            uf: 'PB',
            img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
            paradas: 3,
            tipo: 'oficial'
        },
        {
            id: 102,
            titulo: 'História & Gastronomia',
            subtitulo: 'Arte barroca no São Francisco e culinária paraibana autêntica no Mangai.',
            duracao: '4 Horas',
            tag: 'Cultura',
            tagColor: 'text-danger',
            badgeBg: 'bg-danger',
            cidade: 'João Pessoa',
            uf: 'PB',
            img: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=800&q=80',
            paradas: 2,
            tipo: 'oficial'
        }
    ],
    'Bonito': [
        {
            id: 1,
            titulo: 'Águas Cristalinas & Cavernas',
            subtitulo: 'Flutuação de alta visibilidade no Rio Sucuri e exploração da Gruta do Lago Azul.',
            duracao: '2 Dias',
            tag: 'Ecoturismo',
            tagColor: 'text-success',
            badgeBg: 'bg-success',
            cidade: 'Bonito',
            uf: 'MS',
            img: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
            paradas: 3,
            tipo: 'oficial'
        },
        {
            id: 2,
            titulo: 'Aventura nas Corredeiras & Sabores',
            subtitulo: 'Bóia cross no Rio Formoso com parada gastronômica na Casa do João.',
            duracao: '1 Dia',
            tag: 'Aventura',
            tagColor: 'text-warning',
            badgeBg: 'bg-warning text-dark',
            cidade: 'Bonito',
            uf: 'MS',
            img: 'https://images.unsplash.com/photo-1533230491024-e22d9976da28?auto=format&fit=crop&w=800&q=80',
            paradas: 2,
            tipo: 'oficial'
        }
    ],
    'Recife': [
        {
            id: 201,
            titulo: 'Recife Antigo & Olinda Histórica',
            subtitulo: 'Marco Zero, Instituto Ricardo Brennand e o rico acervo colonial pernambucano.',
            duracao: '1 Dia',
            tag: 'Cultura & Arte',
            tagColor: 'text-danger',
            badgeBg: 'bg-danger',
            cidade: 'Recife',
            uf: 'PE',
            img: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=800&q=80',
            paradas: 3,
            tipo: 'oficial'
        },
        {
            id: 202,
            titulo: 'Praia de Boa Viagem & Gastronomia',
            subtitulo: 'Caminhada na orla dos arrecifes e os melhores pratos com frutos do mar da região.',
            duracao: '4 Horas',
            tag: 'Lazer',
            tagColor: 'text-primary',
            badgeBg: 'bg-primary',
            cidade: 'Recife',
            uf: 'PE',
            img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
            paradas: 2,
            tipo: 'oficial'
        }
    ],
    'Natal': [
        {
            id: 301,
            titulo: 'Dunas & Emoção em Genipabu',
            subtitulo: 'Passeio de buggy nas dunas móveis com esquibunda e lagoas refrescantes.',
            duracao: '1 Dia',
            tag: 'Aventura',
            tagColor: 'text-warning',
            badgeBg: 'bg-warning text-dark',
            cidade: 'Natal',
            uf: 'RN',
            img: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
            paradas: 3,
            tipo: 'oficial'
        },
        {
            id: 302,
            titulo: 'Ponta Negra & Forte dos Reis Magos',
            subtitulo: 'Orla do Morro do Careca com visita à fortificação histórica de 1598.',
            duracao: '1 Dia',
            tag: 'História & Praia',
            tagColor: 'text-primary',
            badgeBg: 'bg-primary',
            cidade: 'Natal',
            uf: 'RN',
            img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
            paradas: 2,
            tipo: 'oficial'
        }
    ],
    'São Paulo': [
        {
            id: 401,
            titulo: 'Paulista Cultural & Museus',
            subtitulo: 'MASP, centros culturais da Avenida Paulista e gastronomia cosmopolita.',
            duracao: '1 Dia',
            tag: 'Arte & Cultura',
            tagColor: 'text-danger',
            badgeBg: 'bg-danger',
            cidade: 'São Paulo',
            uf: 'SP',
            img: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80',
            paradas: 3,
            tipo: 'oficial'
        },
        {
            id: 402,
            titulo: 'Parque Ibirapuera & Vila Madalena',
            subtitulo: 'Manhã verde no Ibirapuera e tarde de grafites no Beco do Batman com cafés.',
            duracao: '1 Dia',
            tag: 'Urbano & Lazer',
            tagColor: 'text-success',
            badgeBg: 'bg-success',
            cidade: 'São Paulo',
            uf: 'SP',
            img: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
            paradas: 2,
            tipo: 'oficial'
        }
    ]
};

// Expor globalmente no window para compatibilidade com scripts inline dos blades
if (typeof window !== 'undefined') {
    window.PLACES_DATA = PLACES_DATA;
    window.CITIES_DATA = CITIES_DATA;
    window.ROTEIROS_DATA = ROTEIROS_DATA;
}

export default {
    CITIES_DATA,
    PLACES_DATA,
    ROTEIROS_DATA
};
